[0m15:23:03.878073 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018A52C87CE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018A51C34860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018A529B4D40>]}


============================== 15:23:03.889121 | fda2b6b9-12d9-498a-b581-9e09720ea9c6 ==============================
[0m15:23:03.889121 [info ] [MainThread]: Running with dbt=1.8.1
[0m15:23:03.891122 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\florc\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init sales_dashboard', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:23:03.961135 [debug] [MainThread]: Starter project path: C:\Users\florc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m15:23:04.024138 [info ] [MainThread]: 
Your new dbt project "sales_dashboard" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:23:04.027139 [info ] [MainThread]: Setting up your profile.
[0m15:24:43.569618 [error] [MainThread]: Encountered an error:

[0m15:24:43.649633 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\florc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\florc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\florc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\main.py", line 469, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\florc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 347, in run
    self.setup_profile(profile_name)
  File "C:\Users\florc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 263, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\florc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 180, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\florc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 164, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\florc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 130, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\florc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\florc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m15:24:43.649633 [debug] [MainThread]: Command `dbt init` failed at 15:24:43.649633 after 100.04 seconds
[0m15:24:43.649633 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018A52CC3290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018A531A5AF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018A5309D820>]}
[0m15:24:43.649633 [debug] [MainThread]: Flushing usage events
